name: Call Reusable Release Workflow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string
      description:
        description: 'Release description'
        required: true
        type: string
      babylon_version:
        description: 'Compatible Babylon version tag'
        required: true
        type: string
      prerelease:
        description: 'Whether prerelease is enabled'
        required: true
        type: boolean
        default: true

jobs:
  call-reusable-release:
    uses: maiquanghiep/.github/.github/workflows/reusable_github_release.yml@hiep/test-release-note
    with:
      tag: ${{ inputs.tag }}
      description: ${{ inputs.description }}
      changelog_path: "https://github.com/maiquanghiep/.github/blob/hiep/test-release-note/CHANGELOG.md"
      build_from_source: true
      build_command: "make build # BABYLON_BUILD_OPTIONS=\"testnet\" make build"
      run_docker: true
      dependencies_enabled: true
      dependencies: "This release is compatible with [Babylon ${{ inputs.babylon_version }}](https://github.com/babylonlabs-io/babylon/releases/tag/${{ inputs.babylon_version }})"
      prerelease: ${{ inputs.prerelease }}
      docker_image_table_template: |
        # 🐳 Custom Docker Image
    
        | Image | Description |
        |-----------------|----------------|
        | babylonlabs/babylond:v0.3.0 | Mainnet image |
        | babylonlabs/babylond:v0.3.0-testnet | Testnet image |
    secrets: inherit
